/* (c) Mathigon, generated by Mathigon Studio */
"use strict";
(() => {
  // frontend/course-custom.ts
  document.addEventListener("DOMContentLoaded", function() {
    const tutorButton = document.querySelector(".tutor-button");
    const skipButton = document.querySelector(".action-skip");
    const revealButton = document.querySelector(".action-reveal");
    const trailerButton = document.querySelector(".action-trailer");
    const sectionItems = document.querySelectorAll(".section-item");
    initializeProgressCircles();
    if (tutorButton) {
      tutorButton.addEventListener("click", function() {
        console.log("Tutor button clicked!");
      });
      setTimeout(() => {
        tutorButton.classList.add("animate-pulse");
        setTimeout(() => {
          tutorButton.classList.remove("animate-pulse");
        }, 2e3);
      }, 5e3);
    }
    if (skipButton) {
      skipButton.addEventListener("click", function() {
        console.log("Skip to next step");
      });
    }
    if (revealButton) {
      revealButton.addEventListener("click", function() {
        console.log("Reveal all content");
        revealAllContent();
      });
    }
    sectionItems.forEach((item) => {
      if (!item.classList.contains("active")) {
        item.addEventListener("mouseenter", function() {
          this.classList.add("hover");
        });
        item.addEventListener("mouseleave", function() {
          this.classList.remove("hover");
        });
      }
    });
    function initializeProgressCircles() {
      const circles = document.querySelectorAll(".progress-fill");
      circles.forEach((circle) => {
        setTimeout(() => {
          circle.classList.add("animate");
        }, 300);
      });
    }
    function revealAllContent() {
      const hiddenElements = document.querySelectorAll(".hidden-step");
      hiddenElements.forEach((element, index) => {
        setTimeout(() => {
          element.classList.add("revealed");
          element.classList.remove("hidden-step");
        }, index * 200);
      });
      const stepMessage = document.querySelector(".step-message");
      if (stepMessage) {
        stepMessage.style.display = "none";
      }
    }
    initializeInteractiveElements();
    function initializeInteractiveElements() {
      const inputs = document.querySelectorAll(".blank-input");
      inputs.forEach((input) => {
        input.addEventListener("keyup", function() {
          validateInput(this);
        });
      });
    }
    function validateInput(input) {
      const correctAnswer = input.getAttribute("data-answer");
      const currentValue = input.value.trim();
      if (currentValue === correctAnswer) {
        input.classList.add("correct");
        input.classList.remove("incorrect");
        checkStepCompletion();
      } else if (currentValue.length > 0) {
        input.classList.add("incorrect");
        input.classList.remove("correct");
      }
    }
    function checkStepCompletion() {
      const currentStep = document.querySelector(".step.active");
      const inputs = currentStep.querySelectorAll(".blank-input");
      let allCorrect = true;
      inputs.forEach((input) => {
        if (!input.classList.contains("correct")) {
          allCorrect = false;
        }
      });
      if (allCorrect) {
        const nextStep = currentStep.nextElementSibling;
        if (nextStep && nextStep.classList.contains("step")) {
          nextStep.classList.remove("hidden-step");
          nextStep.classList.add("active");
          setTimeout(() => {
            nextStep.scrollIntoView({ behavior: "smooth", block: "start" });
          }, 300);
        }
      }
    }
  });
})();